### ISSUE TITLE
get rid of the back button

### ISSUE THREAD

**Issue by markab4** [android-on-track/on-track#6]
we need to get rid of the back button on the mockups. android phones come with a back button already

on my original mockups, you could see the buttons for "back" and "home" on there. we should get those back.

**Comment by markab4** [comment]
Get rid of back button on left side of navigation. Add user profile button on right side of the navigation. 

Assign issue to Mark for review when complete.

**Comment by JazmynFuller** [comment]
I completed this request sir

**Comment by markab4** [comment]
Looks good. Closing issue.
